- name: Preview network state ollama (debug)
  debug:
    msg: >-
      Ollama network will be {{
        (enabled_services | default([]) | intersect(['ollama','karakeep']) | length > 0)
        | ternary('present','absent')
      }}

- name: Ensure ollama networks is in the right state
  community.docker.docker_network:
    name: ollama
    driver: bridge
    state: >-
      {{
        (enabled_services | default([]) | intersect(['ollama','karakeep']) | length > 0)
        | ternary('present','absent')
      }}